# Dockerfile to build custom image for melodic with nvidia gpu
# ARG ros_distro=melodic

# FROM nvidia/cudagl:11.4.2-base-ubuntu18.04
FROM nvidia/cuda:12.6.1-base-ubuntu24.04
# FROM osrf/ros:melodic-desktop-full

ARG ros_distro=jazzy
ENV ROS_DISTRO=$ros_distro
ARG cuda_ver=12.6.1
ARG UID
ARG GID

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Singapore

# remove for integrated graphics
# allow nvidia container toolkit
ENV NVIDIA_VISIBLE_DEVICES \
    ${NVIDIA_VISIBLE_DEVICES:-all}
ENV NVIDIA_DRIVER_CAPABILITIES \
    ${NVIDIA_DRIVER_CAPABILITIES:+$NVIDIA_DRIVER_CAPABILITIES,}graphics,compute,utility,display

# Env for cuda
ENV LD_LIBRARY_PATH=/usr/local/cuda-${cuda_ver}/lib64:$LD_LIBRARY_PATH
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-${cuda_ver}/lib64
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
ENV PATH=/usr/local/cuda-${cuda_ver}/bin:$PATH
ENV CUDA_ROOT=/usr/local/cuda-${cuda_ver}

RUN rm /etc/apt/sources.list.d/cuda.list

# # enable auto completion for apt install
COPY config_${ros_distro}/docker-clean /root/docker-clean
RUN cp /root/docker-clean /etc/apt/apt.conf.d/docker-clean && \
    rm /root/docker-clean

# setup locale (removed sudo from apt-get, locale and update lines)
RUN apt-get update && apt-get upgrade -y && apt-get -y install locales && \
    locale-gen en_US en_US.UTF-8 && \
    update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 && \
    export LANG=en_US.UTF-8

# Ensure Ubuntu Universe repository is enabled
RUN apt-get install -y software-properties-common apt-transport-https
RUN add-apt-repository universe

# Install packages
RUN apt-get update && apt-get upgrade -y && apt-get install -q -y --no-install-recommends sudo \
    curl \
    wget \
    cmake \
    openssh-server \
    htop \
    git \
    libopenmpi-dev \
    python3-dev \
    python3-pip \
    zlib1g-dev \
    make \
    gcc \
    libgtk-3-dev \
    libwebkit2gtk-4.1-dev \
    libffi-dev \
    lsb-release \
    tmux \
    # freeglut3 \
    # freeglut3-dev \
    python3-gst-1.0 \
    libglib2.0-dev \
    ubuntu-restricted-extras \
    libgstreamer-plugins-base1.0-dev \
    nmap \
    dbus-x11 \
    xdg-utils \
    virtualenv \
    mesa-utils \
    python3-colcon-common-extensions

# Install ROS
# setup keys and source.list
# ENV ROS_APT_SOURCE_VERSION=$(curl -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest | grep -F "tag_name" | awk -F\" '{print $4}')
# RUN curl -L -o /tmp/ros2-apt-source.deb "https://github.com/ros-infrastructure/ros-apt-source/releases/download/${ROS_APT_SOURCE_VERSION}/ros2-apt-source_${ROS_APT_SOURCE_VERSION}.$(. /etc/os-release && echo $VERSION_CODENAME)_all.deb"
# RUN dpkg -i /tmp/ros2-apt-source.deb

RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add -
RUN sh -c 'echo "deb [arch=$(dpkg --print-architecture)] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros2-latest.list'

# install ros packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    ros-$ros_distro-desktop-full \ 
    python3-rosdep \
    build-essential
    
# Install sublime & terminator
RUN wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
RUN echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
RUN apt-get update && apt-get install -y sublime-text terminator nautilus 

# Force Install of missing dependencies
RUN apt-get -y -f install && rm -rf /var/lib/apt/lists/*

# Copy bashrc
COPY config_${ros_distro}/bashrc /root/.bashrc

# add user ID to docker container
RUN /bin/bash -c 'echo -e "export USER='root'" >> /root/.bashrc && source /root/.bashrc'

# install virtualenv and create venv
# RUN /bin/bash -c 'mkdir /root/venv && cd /root/venv && \
#                 virtualenv --python=python3.7 py3.7 && \
#                 source /root/venv/py3.7/bin/activate'

# Set path to virtualenv
# ENV PATH /root/venv/py3.7:$PATH

# make workspace & install dependencies
# RUN /bin/bash -c 'echo -e "source /root/venv/py3.7/bin/activate\nsource /opt/ros/melodic/setup.bash" >> /root/.bashrc && source /root/.bashrc'

# setup for terminator
COPY config_${ros_distro}/terminator_config /root/.config/terminator/config

# Make SSH available
EXPOSE 22

# copy entrypoint
COPY config_${ros_distro}/ros_entrypoint_$ROS_DISTRO.sh /ros_entrypoint.sh 

# setup entrypoint for docker 
WORKDIR /root
ENTRYPOINT ["/ros_entrypoint.sh"]
CMD [". ~/.bashrc"]

# # tmux
# RUN /bin/bash -c 'git clone https://github.com/tmux-plugins/tpm /home/$USERNAME/.tmux/plugins/tpm'
# COPY docker/config/tmux.conf /home/$USERNAME/.tmux.conf 
# CMD [". ~/.bashrc"]